name: Just Eat Genoa Bike Monitor

on:
  workflow_dispatch:

  schedule:
    - cron: "17 * * * *"

jobs:
  check-bike:
    runs-on: ubuntu-latest
    timeout-minutes: 70

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requests
        run: pip install requests

      - name: Check Just Eat every 5 minutes
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          for i in {1..12}
          do
            echo "======================================"
            echo "Check $i of 12"
            python github_monitor.py

            if [ "$i" -lt 12 ]; then
              echo "Waiting 5 minutes..."
              sleep 300
            fi
          done
